### PR TITLE
*: add options for setting the body of a DELETE request

### LINKED ISSUE #90: Add support for DeletionPropagation
When deleting a job the spawned pods persist after the job has been deleted. The `kubectl` command as well as the API does support removing the related pods with one delete command using `DeletionPropagation`.

---

Trying to achieve this behaviour with `k8s.QueryParam()` leads to an error:

```go
[...]
        job := &batchv1.Job{}

        if err := client.Get(ctx, "default", name, job); err != nil {
                t.Fatalf("client.Get failed: %s", err)
        }

        if err := client.Delete(ctx, job, k8s.QueryParam("propagationPolicy", "Background")); err != nil {
                t.Fatalf("client.Delete failed: %s", err)
        }
[...]
```

> client.Delete failed: kubernetes api: Failure 400 converting (url.Values).[]string.[]string to (v1.DeleteOptions).*v1.DeletionPropagation.v1.DeletionPropagation: couldn't copy '[]string' into 'v1.DeletionPropagation'; didn't understand types

---

Also passing `*"github.com/ericchiang/k8s/apis/meta/v1".DeleteOptions` as an `k8s.Option` does not work:

> cannot use *"github.com/ericchiang/k8s/apis/meta/v1".DeleteOptions literal (type *"github.com/ericchiang/k8s/apis/meta/v1".DeleteOptions) as type k8s.Option in argument to client.Client.Delete: *"github.com/ericchiang/k8s/apis/meta/v1".DeleteOptions does not implement k8s.Option (missing k8s.updateURL method)

---

In order to delete the pods using the API it seems there must be a JSON payload in the `DELETE` request: https://github.com/kubernetes/kubernetes/issues/20902#issuecomment-321216843

---

So far it seems to me the only current way to clean up the pods as well is to collect them before deleting the job and delete them in separate requests which could be far more easy using the DeletionPropagation.

### PR DESCRIPTION
**Pull request by ericchiang**
closes #90 

cc @Luzifer for any feedback

### CODE REVIEW

File: client.go [hunk 1]
```diff
@@ -383,7 +383,16 @@ func (c *Client) Delete(ctx context.Context, req Resource, options ...Option) er
 	if err != nil {
 		return err
 	}
-	return c.do(ctx, "DELETE", url, nil, nil)
+	o := &deleteOptions{
+		Kind:              "DeleteOptions",
+		APIVersion:        "v1",
+		PropagationPolicy: "Background",
```
Comment (Luzifer) [inline client.go]: This is a change in behaviour: Previously the library used `Orphan` (by not setting a propagation policy). Is this intended? IMHO this would be a major change as it breaks with previous behaviour.

**Comment by Luzifer** [comment]
@ericchiang any news on this?

**Comment by ericchiang** [comment]
Sorry for taking so long. I was taking a break from coding between jobs.
